# -*- coding: UTF-8 -*-
'''
@Project     ：EM_ERP_BAKEN_SANIC 
@File        ：zsk_api.py
@IDE         ：PyCharm 
-------------------------------------
@Author      ：Coisin
@QQ          ：2849068933
@PHONE       ：17350199092
@Description ：
@Date        ：2025-04-09 16:57 
-------------------------------------
'''
# Example Code generated by Beijing Volcanoengine Technology.
from __future__ import print_function
import volcenginesdkcore
import volcenginesdktranslate20250301
from volcenginesdkcore.rest import ApiException
if __name__ == '__main__':
    ak = "AKLTMWE0ZTQwNzFjNjdmNGIxNGFlZDQ0ZGY4ZDczN2NjNDM"
    sk = "T0dJMU5URXpZak5pWVRBNU5HUXpNR0V6TkdZMk5XTXdNR1U0TlRNelpEZw=="
    # 注意示例代码安全，代码泄漏会导致AK/SK泄漏，有极大的安全风险。
    configuration = volcenginesdkcore.Configuration()
    configuration.ak = ak
    configuration.sk = sk
    configuration.region = "cn-beijing"
    # set default configuration
    volcenginesdkcore.Configuration.set_default(configuration)
    # use global default configuration
    api_instance = volcenginesdktranslate20250301.TRANSLATE20250301Api()
    translate_text_request = volcenginesdktranslate20250301.TranslateTextRequest(
        target_language="zh",
        text_list=["Wearable electronic devices and technologies - Part 201-4: Electronic textile - Test method for determining sheet resistance of conductive fabrics after abrasion IEC 63203-201-4:20204 specifies a test procedure to measure the sheet resistance of conductive fabrics after abrasion treatment using the Martindale abrasion machine. This document is applicable to woven, knitted conductive fabrics, conductive nonwovens, coated conductive fabrics, and embroidery fabrics using conductive yarns."]
    )
    try:
        # 复制代码运行示例，请自行打印API返回值。
        resp = api_instance.translate_text(translate_text_request)
        print(resp.translation_list)
    except ApiException as e:
        # 复制代码运行示例，请自行打印API错误信息。
        # print("Exception when calling api: %s\n" % e)
        pass



